name: eslint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install eslint
        run: npm install eslint@7.32.0

      - name: run eslint
        run: npx eslint .
          --config .eslintrc.json
          --ext .js
