name: njsscan

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      # nosemrep yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned
      uses: ajinabraham/njsscan-action@v7
      with:
        args: '. -w'
